version: "2"
services:
  saevis-web:
    build: saevis-web
    ports:
      - 80:80
      - 443:443
    environment:
      - SERVER_URL=http:\/\/localhost:3000
  server:
    build: server
    ports:
      - 3000:3000
